name: shoply
description: "shop app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  internet_connection_checker: any
  flutter:
    sdk: flutter

  #firebase
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0

  # Notifications
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.2
  googleapis_auth: ^1.6.0
#  awesome_notifications: ^0.9.3+1





  #core
#  very_good_analysis: ^5.1.0
  connectivity_plus: ^6.0.3
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
#  flutter_launcher_icons: ^0.13.1
#  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0
  google_fonts: ^6.2.1
  flutter_translate: ^4.1.0
  get_it: ^7.7.0
  package_info_plus: ^8.0.2
  equatable: ^2.0.5

  #language
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #UI
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  animate_do: ^3.3.4
  animations: ^2.0.11
  oktoast: ^3.4.0
  awesome_snackbar_content: ^0.1.3
  font_awesome_flutter: ^10.7.0
  flutter_zoom_drawer: ^3.2.0
  shimmer: ^3.0.0
  flutter_swipe_action_cell: ^3.1.3
  vibration: ^1.9.0
  cached_network_image: ^3.3.1
  webview_flutter: ^4.8.0
  url_launcher: ^6.3.0
  carousel_slider: ^5.0.0

  #  Image Picker
  image_picker: ^1.1.2
  image_cropper: ^7.0.5
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  card_swiper: ^3.0.1
  path_provider: ^2.1.3


  # bloc
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

#  Shared Preferences
  shared_preferences: ^2.2.3
#  freezed:
  freezed_annotation: ^2.4.1

# APIs
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  dropdown_search: ^5.0.6
# Data Source database Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
#    core
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
  hive_generator: ^2.0.1

#  freezed
# dart run build_runner build --delete-conflicting-outputs
  freezed: ^2.5.2
  build_runner: ^2.4.11


#  APIs
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0




flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/core/android_ios_splash_12.png"
  adaptive_icon_background: "assets/images/core/launcher_background.png"
  adaptive_icon_foreground: "assets/images/core/launcher_foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.dev
    - .env.prod
    - .env.firebase
    - assets/images/admin/
    - assets/images/core/
    - assets/images/customer/
    - assets/images/json/
    - assets/images/svg/
    - translations/ar.json
    - translations/en.json

  fonts:
    # Arabic Font
    - family: Cairo
      fonts:
        - asset: assets/fonts/arabic/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/cairo/Cairo-Regular.ttf
          weight: 400
    # English Font
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/poppins/Poppins-Regular.ttf
          weight: 400
