// Mocks generated by Mockito 5.4.6 from annotations
// in shoply/test/features/admin/categories/data/data_source/admin_categories_api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shoply/features/admin/categories/data/data_source/admin_categories_api_service.dart'
    as _i6;
import 'package:shoply/features/admin/categories/data/model/create/create_category_response.dart'
    as _i3;
import 'package:shoply/features/admin/categories/data/model/delete/delete_response.dart'
    as _i5;
import 'package:shoply/features/admin/categories/data/model/get_all_categories/get_all_categories.dart'
    as _i2;
import 'package:shoply/features/admin/categories/data/model/update/update_category_response.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetAllCategoriesResponse_0 extends _i1.SmartFake
    implements _i2.GetAllCategoriesResponse {
  _FakeGetAllCategoriesResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateCategoryResponse_1 extends _i1.SmartFake
    implements _i3.CreateCategoryResponse {
  _FakeCreateCategoryResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateCategoryResponse_2 extends _i1.SmartFake
    implements _i4.UpdateCategoryResponse {
  _FakeUpdateCategoryResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteCategoryResponse_3 extends _i1.SmartFake
    implements _i5.DeleteCategoryResponse {
  _FakeDeleteCategoryResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdminCategoriesApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminCategoriesApiService extends _i1.Mock
    implements _i6.AdminCategoriesApiService {
  MockAdminCategoriesApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.GetAllCategoriesResponse> getAllCategories(
          Map<String, dynamic>? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [query],
        ),
        returnValue: _i7.Future<_i2.GetAllCategoriesResponse>.value(
            _FakeGetAllCategoriesResponse_0(
          this,
          Invocation.method(
            #getAllCategories,
            [query],
          ),
        )),
      ) as _i7.Future<_i2.GetAllCategoriesResponse>);

  @override
  _i7.Future<_i3.CreateCategoryResponse> createCategory(
          Map<String, dynamic>? mutation) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCategory,
          [mutation],
        ),
        returnValue: _i7.Future<_i3.CreateCategoryResponse>.value(
            _FakeCreateCategoryResponse_1(
          this,
          Invocation.method(
            #createCategory,
            [mutation],
          ),
        )),
      ) as _i7.Future<_i3.CreateCategoryResponse>);

  @override
  _i7.Future<_i4.UpdateCategoryResponse> updateCategory(
          Map<String, dynamic>? mutation) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [mutation],
        ),
        returnValue: _i7.Future<_i4.UpdateCategoryResponse>.value(
            _FakeUpdateCategoryResponse_2(
          this,
          Invocation.method(
            #updateCategory,
            [mutation],
          ),
        )),
      ) as _i7.Future<_i4.UpdateCategoryResponse>);

  @override
  _i7.Future<_i5.DeleteCategoryResponse> deleteCategory(
          Map<String, dynamic>? mutation) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [mutation],
        ),
        returnValue: _i7.Future<_i5.DeleteCategoryResponse>.value(
            _FakeDeleteCategoryResponse_3(
          this,
          Invocation.method(
            #deleteCategory,
            [mutation],
          ),
        )),
      ) as _i7.Future<_i5.DeleteCategoryResponse>);
}
