// Mocks generated by Mockito 5.4.6 from annotations
// in shoply/test/features/admin/products/domain/use_cases/admin_product_use_cases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shoply/core/app/Networking/data_result.dart' as _i2;
import 'package:shoply/features/admin/products/data/model/create_product/create_product_response.dart'
    as _i6;
import 'package:shoply/features/admin/products/data/model/delete_category/delete_product.dart'
    as _i10;
import 'package:shoply/features/admin/products/data/model/update_product/update_product_response.dart'
    as _i8;
import 'package:shoply/features/admin/products/domain/entities/create_product_entity.dart'
    as _i7;
import 'package:shoply/features/admin/products/domain/entities/get_product_entity.dart'
    as _i5;
import 'package:shoply/features/admin/products/domain/entities/update_product_entity.dart'
    as _i9;
import 'package:shoply/features/admin/products/domain/repositories/base_admin_product_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataResult_0<T> extends _i1.SmartFake implements _i2.DataResult<T> {
  _FakeDataResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BaseAdminProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseAdminProductRepository extends _i1.Mock
    implements _i3.BaseAdminProductRepository {
  MockBaseAdminProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataResult<List<_i5.GetProductEntity>>> getAllProducts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [],
        ),
        returnValue:
            _i4.Future<_i2.DataResult<List<_i5.GetProductEntity>>>.value(
                _FakeDataResult_0<List<_i5.GetProductEntity>>(
          this,
          Invocation.method(
            #getAllProducts,
            [],
          ),
        )),
      ) as _i4.Future<_i2.DataResult<List<_i5.GetProductEntity>>>);

  @override
  _i4.Future<_i2.DataResult<_i6.CreateProductResponse>> createProduct(
          _i7.CreateProductEntity? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProduct,
          [body],
        ),
        returnValue:
            _i4.Future<_i2.DataResult<_i6.CreateProductResponse>>.value(
                _FakeDataResult_0<_i6.CreateProductResponse>(
          this,
          Invocation.method(
            #createProduct,
            [body],
          ),
        )),
      ) as _i4.Future<_i2.DataResult<_i6.CreateProductResponse>>);

  @override
  _i4.Future<_i2.DataResult<_i8.UpdateProductResponse>> updateProduct(
          _i9.UpdateProductEntity? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [body],
        ),
        returnValue:
            _i4.Future<_i2.DataResult<_i8.UpdateProductResponse>>.value(
                _FakeDataResult_0<_i8.UpdateProductResponse>(
          this,
          Invocation.method(
            #updateProduct,
            [body],
          ),
        )),
      ) as _i4.Future<_i2.DataResult<_i8.UpdateProductResponse>>);

  @override
  _i4.Future<_i2.DataResult<_i10.DeleteProductResponse>> deleteProduct(
          String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [productId],
        ),
        returnValue:
            _i4.Future<_i2.DataResult<_i10.DeleteProductResponse>>.value(
                _FakeDataResult_0<_i10.DeleteProductResponse>(
          this,
          Invocation.method(
            #deleteProduct,
            [productId],
          ),
        )),
      ) as _i4.Future<_i2.DataResult<_i10.DeleteProductResponse>>);
}
