

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    # Clean and build the APK
    sh "flutter clean"
    sh "flutter build apk --release --flavor production -t lib/main_production.dart --no-tree-shake-icons --verbose"

    # Distribute the APK to Firebase App Distribution
    firebase_app_distribution(
      app: ENV['Android_App'],
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
      android_artifact_type: "APK",
      android_artifact_path: '../build/app/outputs/flutter-apk/app-production-release.apk',
      testers: "marconbishay@gmail.com",
      release_notes: "First Fastlane Firebase Distribution",
    )
  end
end
#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
#
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end
#
#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end