name: Android Fastlane with Firebase App Distribution Workflow
on:
  push:
    branches:
      - master
jobs:
    distribute_to_firebase:
      runs-on: ubuntu-latest
      steps:
      - name: checkout my repo code,
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          working-directory: android

      - name: Build and Distribute App
        env:
          FIREBASE_APP_ID: ${{ secrets.ANDROID_APP_ID }}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run:
          bundle exec fastlane android firebase_distribution
        working-directory: android
