name: Android Fastlane with Firebase App Distribution Workflow
on:
  push:
    branches:
      - master
jobs:
    distribute_to_firebase:
      runs-on: ubuntu-latest
      steps:
      - name: checkout my repo code,
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.2.0'
      #     bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      #     working-directory: android
      - run: flutter clean
      - run: flutter build apk --release --flavor production -t lib/main_production.dart --no-tree-shake-icons
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          ANDROID_APP_ID: ${{secrets.ANDROID_APP_ID}}
          FIREBASE_CLI_TOKEN: ${{secrets.FIREBASE_CLI_TOKEN}}
          groups: pre-tester
          file: build/app/outputs/apk/release/app-release.apk
#      - name: Build and Distribute App
#        with:
#          FIREBASE_CLI_TOKEN: ${{secrets.FIREBASE_CLI_TOKEN}}
#
#        run:
#          bundle exec fastlane firebase_distribution
#        working-directory: android
