name: Android Fastlane with Firebase App Distribution Workflow


on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.4'


      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Flutter Clean
        run: flutter clean

      - name: Build APK for Production
        run: flutter build apk --release --flavor production -t lib/main_production.dart

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_CLI_TOKEN }}
          groups: pre-tester # Refactor to use a secret for tester group
          file: ../build/app/outputs/flutter-apk/app-production-release.apk
          releaseNotes: "First GitHub Action Firebase Distribution"

      # Optionally, you can add steps for notifications, testing, etc.

